site_name: "Execution Cognition Machine (ECM)"
site_url: "https://SamthinkGit.github.io/GU-systems/"
repo_url: "https://github.com/SamthinkGIt/GU-systems"
docs_dir: "wiki"
theme:
  name: "mkdocs"
