from agent_protocol import Step
from agent_protocol import Task


class ServerAPI:

    def __init__(self, *args, **kwargs) -> None: ...
    def start(self, *args, **kwargs) -> None: ...
    async def task_handler(task: Task) -> None: ...
    async def step_handler(step: Step) -> Step: ...


class ClientAPI:

    def __init__(self, *args, **kwargs) -> None: ...
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type, exc_value, traceback): ...
