name: Deploy Wiki to Pages

# Activar en cambios de la wiki
on:
  gollum: {} # Evento para ediciones de la wiki&#8203;:contentReference[oaicite:7]{index=7}
  # Puedes añadir triggers manuales o programados si lo deseas:
  # push:
  #   branches: [ main ]
  #   paths: [ "mkdocs.yml" ]  # por ejemplo, para re-deploy cuando cambia la config
  workflow_dispatch: {}      # permite ejecutarlo manualmente desde la pestaña Actions

permissions:
  contents: write # Necesario para poder hacer push a Pages (gh-pages branch)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del repositorio principal (para acceder a mkdocs.yml y quizás otros archivos necesarios)
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE/wiki


      # Paso 2: Checkout del repositorio de la Wiki en carpeta "wiki"
      - name: Checkout wiki content
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}.wiki
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: master
          path: wiki

      # Paso 3: Asegurar página de inicio para MkDocs
      - name: Prepare index page
        run: |
          if [ -f "wiki/Home.md" ]; then
            cp wiki/Home.md wiki/index.md
          elif [ ! -f "wiki/index.md" ]; then
            # Si no hay Home.md, crear un índice básico listando páginas
            echo "# Documentation" > wiki/index.md
            echo -e "\n*Welcome to the ECM docs.*\n" >> wiki/index.md
            for FILE in wiki/*.md; do
              NAME=$(basename "$FILE")
              [[ "$NAME" == "index.md" ]] && continue
              TITLE="${NAME%.md}"
              # Reemplazar guiones por espacios para título
              TITLE="${TITLE//-/ }"
              echo "- [${TITLE}](${NAME})" >> wiki/index.md
            done
          fi

      # Paso 4: Instalar MkDocs (y tema Material si se desea)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install MkDocs
        run: |
          pip install mkdocs mkdocs-material

      # Paso 5: Construir el sitio estático con MkDocs
      - name: Build site
        run: mkdocs build # Generará el sitio en la carpeta "site/"

      # Paso 6: Desplegar a GitHub Pages (rama gh-pages)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
